raise Exception("🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣 test.py 강제 에러 🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣🐣")
